version: '3.8'

services:
  # --- BASE DE DATOS MYSQL ---
  db-mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: negociodb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BACKEND (SPRING BOOT) ---
  api-app:
    build: ./backend
    container_name: springboot-container
    ports:
      - "8080:8080"
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/negociodb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  # --- FRONTEND (ANGULAR EN MODO DESARROLLO) ---
  angular-frontend:
    build: ./frontend
    container_name: angular-container
    ports:
      - "4200:4200"
    # Forzamos a Angular a escuchar en todas las interfaces para que sea accesible desde fuera del contenedor
    command: npx ng serve --host 0.0.0.0 --port 4200
    volumes:
      - ./frontend:/app
      # Este volumen anónimo es CLAVE: Protege los node_modules del contenedor 
      # para que no sean borrados ni pisados por los node_modules de tu máquina local
      - /app/node_modules
    depends_on:
      - api-app

volumes:
  mysql_data:
